# Site settings
title: Aggie Artificial Intelligence Society
email: aais@tamu.edu
description: > # this means to ignore newlines until "baseurl:"
  The purpose of AAIS is to provide resources and a sense of community to all interested in A.I., including a forum for discussion for all students interested in A.I., practical A.I. implementations, updates on current research, and career networking.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aais.cs.tamu.edu/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: compressed
